language: rust

rust: nightly

addons:
  apt:
    packages:
    - ruby

# Don't test on macOS for now.
# os:
#   - linux
#   - osx

before_script:
  - rustup component add --toolchain nightly rustfmt

install:
  - git clone https://github.com/aquynh/capstone
  - (cd capstone && git checkout 3.0.4 && sudo make install)

script:
  - cargo fmt -- --check
  - tools/test
  - tools/test-release
