language: rust

rust: nightly

addons:
  apt:
    packages:
    - ruby

install:
  - git clone https://github.com/aquynh/capstone
  - (cd capstone && git checkout 3.0.4 && sudo make install)

before_script:
  - rustup component add --toolchain nightly rustfmt

script:
  - cargo fmt -- --check
  - tools/test
  - tools/test-release
