language: rust

rust: nightly

addons:
  apt:
    packages:
    - ruby
    - libcapstone-dev

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt -- --check
  - tools/test
  - tools/test-release
