[package]
name = "dora"
version = "0.0.1"
authors = ["Dominik Inführ <dominik.infuehr@gmail.com>"]
edition = "2018"

[dependencies]
rustc-serialize = "*"
docopt = "0.7"
byteorder = "*"
libc = "*"
time = "*"
capstone = "*"
dora-parser = { path = "lib/dora-parser" }
threadpool = "*"
crossbeam-deque = "*"
rand = "*"
regex = "*"
scoped_threadpool = "*"
parking_lot = "*"
fixedbitset = "*"
num_cpus = "*"
backtrace = "*"

[profile.release]
panic = "abort"

[lib]
name = "dora"
path = "src/lib.rs"

[[bin]]
name = "dora"
path = "src/main.rs"
