[package]
name = "dora-asm"
version = "0.0.1"
authors = ["Dominik Inführ <dominik.infuehr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.*"
