[package]
name = "dora-parser-fuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "*"
dora-parser = { path = "../dora-parser", version = "0.0.2" }
